language: cpp

dist: trusty
sudo: required

notifications:
  irc:
    channels:
      - "irc.quakenet.org#unrealarena"
    template:
      - "%{repository_slug} (%{branch}) \"%{commit_message}\" [%{result}]"
      - "%{build_url}"
      - "%{compare_url}"

before_install:
  - ./.travis.sh before_install

install:
  - ./.travis.sh install

before_script:
  - ./.travis.sh before_script

script:
  - ./.travis.sh script

before_deploy:
  - ./.travis.sh before_deploy

deploy:
  provider: releases
  api_key:
    secure: dW/l+hEb/f1ZI9F7fI9nsP0SbhNcIs5WsmDK7o+NmcSaitUtBJdkmWLPaaDjYvRiSWPm75o42dYGC0TbOwgLA8q6Qbm4fD3aa7heD/HEgcOGFbTOy6SAKc/JpPzgiJjvkS80RNvT4A7CEz2cHhCon8VuTKHKOJMyI7miouxHMGiJsGNB/LjehtMOX20IKi+cezY/zizXKOdSFd5pEughF2vgfWkakmXc3nWd5rpMk7xMv6UNOKt9Sb+/FA4vsYniWMI4wlvCySRFuKvtcGpVvWPTqU7kDfZ9sMGys5UaCInCJreh4j7IdIkIbXTGwMmT/EjIg5IfzkidiCGDiXYxj08loT3w2dsdZUfeFbCdm4f6F+sHF0yZIlTPY7l3iFK8y9LIIaNFRnxQIpff/o++ApW7wuRX5uQw07D89S6beOxfT1nIF5GmGuOwY+Wie1QZFlFGplEItnP9j70B15lQF8UZ1TWq1Qv/v98ByDhln8B+CfX3/IthW9dM/q1s3SLMkr6xFBSX8Yq3HEY2GlKwrX0lDlGGIjmW+DzYJqzmgaaAoBPFTXduib1mV7cQRhmDfxuSQ4O4hWt430uHeOhnbtND4ZI4TN/+6ZHPyUs0O930b64uBvs+PX0C/UuwGe47oAPbrpc0fSaRzRBCH4XjIVnICqTaxRpKyTVc+0r8/wY=
  file: "unrealarena-data.pre.zip"
  skip_cleanup: true
  prerelease: true
  on:
    tags: true
    repo: unrealarena/unrealarena-data
