language: cpp

compiler: gcc

sudo: required

notifications:
  irc:
    channels:
      - "irc.quakenet.org#unrealarena"
    template:
      - "%{repository_slug} (%{branch}) \"%{commit_message}\" [%{result}]"
      - "%{build_url}"
      - "%{compare_url}"

before_install:
  - ./.travis.sh "before_install"

install:
  - ./.travis.sh "install"

script:
  - ./.travis.sh "script"

deploy:
  provider: releases
  api_key:
    secure: G98qIFo3CZ2VYz3f1+Bx2YtikyP4pr/883uExko3b+M/qT3JSoZ1sGMjEi+JEIFdB3rU44vzRQuYTzk173pYchYhvDBaLC6yz++EyXTgZqTuvbUEHLGP1Ve2MXaFCsFNb6LVOvDbwL1b6Oi/2qEoiyIdLPYj46EVu4wdP0GC+IKzsAkdxP/kD7rnngnKZ8AowGf4viy3/TAhKs7JshoCfcssbMTRBLvWzy8zpsw0XBWaXXUcG2EXRKATCfLAhNlfdnxN+R01kty0kdqTdPYRP3z/P5dQqKIQQULalLxNdmxdeC0o9ltmDWqCqIaCtT+N+H4VYkwPyM7J/gtMgNx4S5h0/5G+tf0UhJ1+2IbHDiLeYPsU1IEVVs6z1+HwHQGj/e+5cShi4AHIdSgWt8Z9PjJE60dXXXvX512OTW2KjTR64CNZsp65EvUWcM2CevNB0mZnpUd5cNOKqOtDPck9h8fKWo/bcbjC/CwgrUUlHN3XororRhnKYnH6UdOtM7C/K/f3Z7zVbysiMUkbsH0dib99+iOQhemYjM0uc5Cws2Ad/7MCd0BB2Wb2dMw6QWDRp1IEn2z80WmmIFwybJBvmY6hWPdl1f6lTBwNfv6pR3uXxJELMW8qLpAbdZBLpO+7okDqrN311hYSDXlXWt7j1cPaGjh46qS1S3yXGZzYsfk=
  file: "unrealarena-data.pre.zip"
  skip_cleanup: true
  prerelease: true
  on:
    tags: true
    repo: unrealarena/unrealarena-data
